- hosts: all
  become: true

  vars:
    nginx_package: nginx
    nginx_config_file: /etc/nginx/sites-available/default.conf
    nginx_port: 80
    nginx_index_file: index.html

  tasks:
    - name: Install Nginx package
      apt:
        name: "{{ nginx_package }}"
        state: present

    - name: Create Nginx configuration file
      template:
        src: default.conf.j2
        dest: "{{ nginx_config_file }}"
      notify: Restart Nginx

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Check Nginx availability
      uri:
        url: "http://localhost:{{ nginx_port }}"
        status_code: 200

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
